version: "3.7"
services:                       # Each service of the docker-compose is a container that will be built (to be reviewed).
  app:
    build: .                    # Run the Dockerfile that is in the current folder (`docker build .`)
    ports:                      # Ports to be exposed
      - "${SENG365_PORT}:4941"
    environment:
      - SENG365_MYSQL_HOST
      - SENG365_MYSQL_USER
      - SENG365_MYSQL_PASSWORD
      - SENG365_MYSQL_DATABASE
    restart: on-failure